name: rumah_sakit_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- Ikon Bawaan ---
  cupertino_icons: ^1.0.8

  # --- FIREBASE UTAMA (Versi Angka) ---
  firebase_core: ^3.10.1 # Versi stabil terbaru
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1

  # --- TAMBAHAN UNTUK FOTO ---
  firebase_storage: ^12.4.1
  image_picker: ^1.0.7
  
  # --- FORMATTING & FONT (PENTING UNTUK UI BAGUS) ---
  intl: ^0.20.2
  google_fonts: ^6.1.0  # <--- INI BARIS BARU YANG KITA TAMBAH

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true